stages:
  - build
  - deploy

build_site:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run clean
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - static/
  artifacts:
    paths:
      - public
  only:
    - main

deploy_production:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync public/ s3://nowyouseeit.com/ --delete --cache-control max-age=31557600,public
    - aws s3 cp s3://nowyouseeit.com s3://nowyouseeit.com --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control public,max-age=0,must-revalidate --content-type text/html
    - aws s3 cp s3://nowyouseeit.com s3://nowyouseeit.com --recursive --exclude "*" --include "*-data.json" --metadata-directive REPLACE --cache-control public,max-age=0,must-revalidate --content-type text/json
    - aws cloudfront create-invalidation --distribution-id E173U2COPVSRZF --paths '/*'
  environment:
    name: PROD
    url: http://nowyouseeit.com
  only:
    - main
