stages:
  - build
  - deploy

build_site:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run clean
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - static/
  artifacts:
    paths:
      - public
  only:
    - main
  rules:
    - when: manual

deploy_production:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync public/ s3://nowyouseeit.com/ --delete --cache-control max-age=31557600,public
    - aws cloudfront create-invalidation --distribution-id E173U2COPVSRZF --paths '/*'
  environment:
    name: PROD
    url: http://nowyouseeit.com
  only:
    - main
  rules:
    - when: manual
