stages:
  - build
  - deploy

build_site:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run clean
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  only:
    - master
    - tags

deploy_production:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync public/ s3://nowyouseeitblog/ --delete --cache-control max-age=31557600,public
    - aws cloudfront create-invalidation --distribution-id E1MH1GB0WBFG9N --paths '/*' && aws cloudfront create-invalidation --distribution-id E1L7N8HRHGPEL6 --paths '/*'
  environment:
    name: PROD
    url: http://nowyouseeit.blog
  only:
    - master
